
//import com.mysql.jdbc.PreparedStatement;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sajid
 */
public class first extends javax.swing.JFrame {

    /**
     * Creates new form first
     */
    public static Timer t;
    public static exam_dtl ex;
    public static PreparedStatement pst=null;
    public static int ques_num = 0,cur_marks=0;
    public static String curIns;
    public static String curExm;
    public static String instr;
    public static Connection con = null;
    public static ResultSet rs=null;
    public static int que_pg_num=1,min,sec;
    public static ArrayList<pdf> pdf1 =new ArrayList<>();

    public first() {
        initComponents();
        Te_log.setVisible(false);
        set_exam.setVisible(false);
        ExamAdd.setVisible(false);
        set_que.setVisible(false);
        Mark_sheet.setVisible(false);
        exam_strt.setVisible(false);
        exam_page.setVisible(false);
        te_reg.setVisible(false);
        exam_finished.setVisible(false);
        st_name.setText("");
        st_roll.setText("");
        Ex_nm.setText("");
    }

    public Connection getconnection1() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            //JOptionPane.showMessageDialog(null, "connected");

            return con;

        } catch (SQLException ex) {
            Logger.getLogger(first.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "not connected");
            return null;

        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        set_que = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        frst = new javax.swing.JTextField();
        scnd = new javax.swing.JTextField();
        thrd = new javax.swing.JTextField();
        frth = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ques_name = new javax.swing.JTextArea();
        Cor = new javax.swing.JTextField();
        que_num = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        Stdnt_sub = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ex_nm = new javax.swing.JTextField();
        st_roll = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Submit_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        st_name = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        Te_log = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        log_pass = new javax.swing.JPasswordField();
        log_name = new javax.swing.JTextField();
        lgin_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        set_exam = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        search_exam = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        exam_table = new javax.swing.JTable();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        ExamAdd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ins = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Exam_name = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        Time = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        Time1 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        Mark_sheet = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        marks_table = new javax.swing.JTable();
        jSeparator13 = new javax.swing.JSeparator();
        exam_strt = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        E_NAM = new javax.swing.JLabel();
        t_time = new javax.swing.JLabel();
        t_marks = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Instr_area = new javax.swing.JTextArea();
        exam_page = new javax.swing.JPanel();
        op1_radio = new javax.swing.JRadioButton();
        op2_radio = new javax.swing.JRadioButton();
        op3_radio = new javax.swing.JRadioButton();
        op4_radio = new javax.swing.JRadioButton();
        Next_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Timer_ = new javax.swing.JLabel();
        que_num_ex_pg = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        ex_pg_ques = new javax.swing.JTextArea();
        te_reg = new javax.swing.JPanel();
        tec_pass = new javax.swing.JTextField();
        tec_name = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        exam_finished = new javax.swing.JPanel();
        pdf_button = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ob_marks = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        total_marks = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        set_que.setBackground(new java.awt.Color(0, 102, 153));
        set_que.setForeground(new java.awt.Color(255, 255, 255));
        set_que.setMinimumSize(new java.awt.Dimension(500, 500));
        set_que.setPreferredSize(new java.awt.Dimension(500, 500));
        set_que.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 102, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Setup Question");
        set_que.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 140, 27));

        jLabel10.setBackground(new java.awt.Color(0, 102, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correct Ans:");
        set_que.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 153, 31));

        frst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frstActionPerformed(evt);
            }
        });
        set_que.add(frst, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 227, 117, -1));
        set_que.add(scnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 279, 117, -1));

        thrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thrdActionPerformed(evt);
            }
        });
        set_que.add(thrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 337, 117, -1));
        set_que.add(frth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 387, 117, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 153));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("a.");
        set_que.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 102, 153));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("c.");
        set_que.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 20, -1));

        jLabel14.setBackground(new java.awt.Color(0, 102, 153));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("d.");
        set_que.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 102, 153));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("b.");
        set_que.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 102, 153));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Set Next Question");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        set_que.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 447, 147, 30));

        jButton11.setBackground(new java.awt.Color(0, 102, 153));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Done");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        set_que.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 447, 153, 30));

        Ques_name.setColumns(20);
        Ques_name.setRows(5);
        Ques_name.setText("Question?");
        jScrollPane2.setViewportView(Ques_name);

        set_que.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 244, -1));
        set_que.add(Cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 70, -1));

        que_num.setText("1.");
        que_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                que_numActionPerformed(evt);
            }
        });
        set_que.add(que_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, -1));
        set_que.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 102, 100, 30));
        set_que.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        Stdnt_sub.setBackground(new java.awt.Color(0, 102, 153));
        Stdnt_sub.setForeground(new java.awt.Color(255, 255, 255));
        Stdnt_sub.setMinimumSize(new java.awt.Dimension(500, 500));
        Stdnt_sub.setPreferredSize(new java.awt.Dimension(500, 500));
        Stdnt_sub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ONLINE EXAM");
        Stdnt_sub.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 65, 177, 64));
        Stdnt_sub.add(Ex_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 170, 45));
        Stdnt_sub.add(st_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 40));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        Stdnt_sub.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 192, 89, 45));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXAM NAME");
        Stdnt_sub.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 89, 40));

        Submit_button.setBackground(new java.awt.Color(0, 102, 153));
        Submit_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Submit_button.setForeground(new java.awt.Color(255, 255, 255));
        Submit_button.setText("SUBMIT");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });
        Stdnt_sub.add(Submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 94, 35));

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Stdnt_sub.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 77, 32));
        Stdnt_sub.add(st_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 194, 170, 45));

        jLabel22.setBackground(new java.awt.Color(0, 102, 153));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ROLL");
        Stdnt_sub.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 89, 40));
        Stdnt_sub.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 20));

        Te_log.setBackground(new java.awt.Color(0, 102, 153));
        Te_log.setForeground(new java.awt.Color(255, 255, 255));
        Te_log.setMinimumSize(new java.awt.Dimension(500, 500));
        Te_log.setPreferredSize(new java.awt.Dimension(500, 500));
        Te_log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 102, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TEACHER LOGIN");
        Te_log.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 58, 194, 97));

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        Te_log.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 286, 77, 27));

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        jLabel6.setToolTipText("");
        Te_log.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 221, 77, 27));
        Te_log.add(log_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 286, 250, 27));
        Te_log.add(log_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 223, 250, 27));

        lgin_btn.setBackground(new java.awt.Color(0, 102, 153));
        lgin_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgin_btn.setForeground(new java.awt.Color(255, 255, 255));
        lgin_btn.setText("LOG IN");
        lgin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgin_btnActionPerformed(evt);
            }
        });
        Te_log.add(lgin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 374, 94, 35));

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Te_log.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 80, 36));

        jButton13.setBackground(new java.awt.Color(0, 102, 153));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Register");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Te_log.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 40));
        Te_log.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, 20));

        set_exam.setBackground(new java.awt.Color(0, 102, 153));
        set_exam.setForeground(new java.awt.Color(255, 255, 255));
        set_exam.setMinimumSize(new java.awt.Dimension(500, 500));
        set_exam.setPreferredSize(new java.awt.Dimension(500, 500));
        set_exam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        set_exam.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 103, 34));

        jLabel7.setBackground(new java.awt.Color(0, 102, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Question Setup");
        set_exam.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 30));

        jButton6.setBackground(new java.awt.Color(0, 102, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add Exam");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        set_exam.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 30));
        set_exam.add(search_exam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        jButton12.setBackground(new java.awt.Color(0, 102, 153));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Marks");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        set_exam.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, 30));

        jLabel26.setBackground(new java.awt.Color(0, 102, 153));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Exam Name");
        set_exam.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));

        exam_table.setBackground(new java.awt.Color(0, 102, 153));
        exam_table.setForeground(new java.awt.Color(255, 255, 255));
        exam_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Exam Name", "Questions", "Time"
            }
        ));
        jScrollPane6.setViewportView(exam_table);

        set_exam.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 460, 170));
        set_exam.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, 20));
        set_exam.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 10));

        ExamAdd.setBackground(new java.awt.Color(0, 102, 153));
        ExamAdd.setMinimumSize(new java.awt.Dimension(500, 500));
        ExamAdd.setPreferredSize(new java.awt.Dimension(500, 500));
        ExamAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ins.setColumns(20);
        Ins.setRows(5);
        jScrollPane1.setViewportView(Ins);

        ExamAdd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 370, 110));

        jLabel8.setBackground(new java.awt.Color(0, 102, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Exam Name");
        ExamAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 11, 167, 46));

        jButton7.setBackground(new java.awt.Color(0, 102, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Add Questions");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        ExamAdd.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, 38));

        jButton8.setBackground(new java.awt.Color(0, 102, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        ExamAdd.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 78, 33));

        jLabel16.setBackground(new java.awt.Color(0, 102, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Instructions");
        ExamAdd.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 167, 46));
        ExamAdd.add(Exam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 84, 176, 41));
        ExamAdd.add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 130, 40));

        Time.setBackground(new java.awt.Color(0, 102, 153));
        Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("Marks:");
        ExamAdd.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 70, 30));
        ExamAdd.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 130, 40));

        Time1.setBackground(new java.awt.Color(0, 102, 153));
        Time1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Time1.setForeground(new java.awt.Color(255, 255, 255));
        Time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1.setText("Time(s):");
        ExamAdd.add(Time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 40));
        ExamAdd.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));
        ExamAdd.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, -1));
        ExamAdd.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 90, 10));
        ExamAdd.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 90, 10));

        Mark_sheet.setBackground(new java.awt.Color(0, 102, 153));
        Mark_sheet.setForeground(new java.awt.Color(255, 255, 255));
        Mark_sheet.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Mark_sheet.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel17.setBackground(new java.awt.Color(0, 102, 153));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Mark Sheet");

        jButton34.setBackground(new java.awt.Color(0, 153, 204));
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("Back");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        marks_table.setBackground(new java.awt.Color(0, 102, 153));
        marks_table.setForeground(new java.awt.Color(255, 255, 255));
        marks_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ROLL", "MARKS", "RANK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(marks_table);

        javax.swing.GroupLayout Mark_sheetLayout = new javax.swing.GroupLayout(Mark_sheet);
        Mark_sheet.setLayout(Mark_sheetLayout);
        Mark_sheetLayout.setHorizontalGroup(
            Mark_sheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mark_sheetLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(Mark_sheetLayout.createSequentialGroup()
                .addGroup(Mark_sheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mark_sheetLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Mark_sheetLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Mark_sheetLayout.setVerticalGroup(
            Mark_sheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mark_sheetLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(Mark_sheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exam_strt.setBackground(new java.awt.Color(0, 102, 153));
        exam_strt.setMinimumSize(new java.awt.Dimension(500, 500));
        exam_strt.setPreferredSize(new java.awt.Dimension(500, 500));
        exam_strt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(0, 102, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Instructions:");
        exam_strt.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 84, 171, 43));

        jButton32.setBackground(new java.awt.Color(0, 153, 204));
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("Start");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        exam_strt.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 429, 129, 31));

        jLabel19.setBackground(new java.awt.Color(0, 102, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total Time");
        exam_strt.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 401, 102, -1));

        jLabel20.setBackground(new java.awt.Color(0, 102, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total Marks");
        exam_strt.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 401, 102, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        exam_strt.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 90, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        exam_strt.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 90, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        exam_strt.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        exam_strt.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 62, 260, 20));

        E_NAM.setBackground(new java.awt.Color(0, 102, 204));
        E_NAM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        E_NAM.setForeground(new java.awt.Color(255, 255, 255));
        E_NAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exam_strt.add(E_NAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 260, 40));

        t_time.setBackground(new java.awt.Color(0, 102, 153));
        t_time.setForeground(new java.awt.Color(255, 255, 255));
        t_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exam_strt.add(t_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 30));

        t_marks.setBackground(new java.awt.Color(0, 102, 204));
        t_marks.setForeground(new java.awt.Color(255, 255, 255));
        t_marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exam_strt.add(t_marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 100, 30));

        Instr_area.setEditable(false);
        Instr_area.setBackground(new java.awt.Color(0, 102, 153));
        Instr_area.setColumns(20);
        Instr_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Instr_area.setForeground(new java.awt.Color(255, 255, 255));
        Instr_area.setRows(5);
        jScrollPane4.setViewportView(Instr_area);

        exam_strt.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 440, 240));

        exam_page.setBackground(new java.awt.Color(0, 102, 153));
        exam_page.setMinimumSize(new java.awt.Dimension(500, 500));
        exam_page.setPreferredSize(new java.awt.Dimension(500, 500));
        exam_page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        op1_radio.setBackground(new java.awt.Color(0, 102, 153));
        op1_radio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op1_radio.setForeground(new java.awt.Color(255, 255, 255));
        exam_page.add(op1_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 190, 30));

        op2_radio.setBackground(new java.awt.Color(0, 102, 153));
        op2_radio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op2_radio.setForeground(new java.awt.Color(255, 255, 255));
        exam_page.add(op2_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 30));

        op3_radio.setBackground(new java.awt.Color(0, 102, 153));
        op3_radio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op3_radio.setForeground(new java.awt.Color(255, 255, 255));
        op3_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3_radioActionPerformed(evt);
            }
        });
        exam_page.add(op3_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 30));

        op4_radio.setBackground(new java.awt.Color(0, 102, 153));
        op4_radio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op4_radio.setForeground(new java.awt.Color(255, 255, 255));
        op4_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4_radioActionPerformed(evt);
            }
        });
        exam_page.add(op4_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 30));

        Next_button.setBackground(new java.awt.Color(0, 102, 153));
        Next_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Next_button.setForeground(new java.awt.Color(255, 255, 255));
        Next_button.setText("Next");
        Next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_buttonActionPerformed(evt);
            }
        });
        exam_page.add(Next_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 150, 40));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Time Remaining:");
        exam_page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 120, 30));

        Timer_.setBackground(new java.awt.Color(0, 102, 153));
        Timer_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Timer_.setForeground(new java.awt.Color(255, 255, 255));
        Timer_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exam_page.add(Timer_, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, 30));

        que_num_ex_pg.setBackground(new java.awt.Color(0, 102, 153));
        que_num_ex_pg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        que_num_ex_pg.setForeground(new java.awt.Color(255, 255, 255));
        que_num_ex_pg.setText("1.");
        exam_page.add(que_num_ex_pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));
        exam_page.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
        exam_page.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 52, 130, 10));

        ex_pg_ques.setBackground(new java.awt.Color(0, 102, 153));
        ex_pg_ques.setColumns(20);
        ex_pg_ques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ex_pg_ques.setForeground(new java.awt.Color(255, 255, 255));
        ex_pg_ques.setRows(5);
        jScrollPane3.setViewportView(ex_pg_ques);

        exam_page.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 120));

        te_reg.setBackground(new java.awt.Color(0, 102, 153));
        te_reg.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        te_reg.setPreferredSize(new java.awt.Dimension(500, 500));

        tec_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tec_passActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 102, 153));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Username");

        jLabel27.setBackground(new java.awt.Color(0, 102, 153));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Password");

        jButton15.setBackground(new java.awt.Color(0, 102, 153));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Register");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(0, 102, 153));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("REGISTRATION");

        jButton14.setBackground(new java.awt.Color(0, 102, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout te_regLayout = new javax.swing.GroupLayout(te_reg);
        te_reg.setLayout(te_regLayout);
        te_regLayout.setHorizontalGroup(
            te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, te_regLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tec_name, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tec_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(te_regLayout.createSequentialGroup()
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(te_regLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jSeparator11))
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(te_regLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        te_regLayout.setVerticalGroup(
            te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(te_regLayout.createSequentialGroup()
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(te_regLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(te_regLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tec_name, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(te_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tec_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        exam_finished.setBackground(new java.awt.Color(0, 102, 153));
        exam_finished.setForeground(new java.awt.Color(255, 255, 255));
        exam_finished.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        exam_finished.setMinimumSize(new java.awt.Dimension(500, 500));

        pdf_button.setBackground(new java.awt.Color(0, 102, 153));
        pdf_button.setForeground(new java.awt.Color(255, 255, 255));
        pdf_button.setText("Generate PDF");
        pdf_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf_buttonActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 102, 153));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("YOUR EXAM IS FINISHED!");

        jLabel25.setBackground(new java.awt.Color(0, 102, 153));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("OBTAINED MARKS:");

        ob_marks.setBackground(new java.awt.Color(0, 102, 153));
        ob_marks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ob_marks.setForeground(new java.awt.Color(255, 255, 255));
        ob_marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ob_marks.setText("0");

        jLabel30.setBackground(new java.awt.Color(0, 102, 153));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("TOTAL MARKS:");

        total_marks.setBackground(new java.awt.Color(0, 102, 153));
        total_marks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_marks.setForeground(new java.awt.Color(255, 255, 255));
        total_marks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_marks.setText("0");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Main Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout exam_finishedLayout = new javax.swing.GroupLayout(exam_finished);
        exam_finished.setLayout(exam_finishedLayout);
        exam_finishedLayout.setHorizontalGroup(
            exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exam_finishedLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(pdf_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(exam_finishedLayout.createSequentialGroup()
                .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exam_finishedLayout.createSequentialGroup()
                        .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(exam_finishedLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(exam_finishedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(exam_finishedLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ob_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(exam_finishedLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(jSeparator7)))
                    .addGroup(exam_finishedLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exam_finishedLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exam_finishedLayout.setVerticalGroup(
            exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exam_finishedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ob_marks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(exam_finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_marks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(pdf_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stdnt_sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Te_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(set_exam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ExamAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(set_que, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Mark_sheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_strt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(te_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_finished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stdnt_sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Te_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(set_exam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ExamAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(set_que, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Mark_sheet, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_strt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(te_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exam_finished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Stdnt_sub.setVisible(false);
        Te_log.setVisible(true);
        set_exam.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Te_log.setVisible(false);
        Stdnt_sub.setVisible(true);
        set_exam.setVisible(false);
        log_name.setText(null);
        log_pass.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lgin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgin_btnActionPerformed
        // TODO add your handling code here:
        if (log_name.getText().equals("")|| log_pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "please insert data!");
        }
        else {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from teacher_info where name =? ");
            
            pst.setString(1, log_name.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
                 String str=rs.getString("pass");
                 if(log_pass.getText().equals(str)){
                        Te_log.setVisible(false);
                        set_exam.setVisible(true);
                        curIns=log_name.getText();

                        try{
                            Connection con=getconnection1();
                            String sql="select name,Time,Marks from exam where Instructor =? ";
                            pst=con.prepareStatement(sql);
                            pst.setString(1, log_name.getText());
                            rs=pst.executeQuery();
                            exam_table.setModel(DbUtils.resultSetToTableModel(rs));

                        }
                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null, "Add You first exam!");
                        }
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
                 }
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_lgin_btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ExamAdd.setVisible(false);
        set_exam.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from exam where name =? ");
            
            pst.setString(1,Exam_name.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
                 JOptionPane.showMessageDialog(null, "Exam is being taken by another Instructor ,please choose another exam name!");
            }
            else{
                ExamAdd.setVisible(false);
                set_que.setVisible(true);
                ex = new exam_dtl(Exam_name.getText(), Ins.getText(),curIns);
                try {
                Connection con = getconnection1();
                java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO exam(name,Instruction,Instructor,Time,Marks)" + "values(?,?,?,?,?)");
                ps.setString(1, Exam_name.getText());
                ps.setString(2, Ins.getText());
                ps.setString(3, curIns);
                ps.setString(4, time.getText());
                ps.setString(5, marks.getText());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Inserted");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }

            }
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        set_que.setVisible(false);
        set_exam.setVisible(true);
            ques e = new ques(Ques_name.getText(), frst.getText(), scnd.getText(), thrd.getText(), frth.getText(), Cor.getText(),ex.exm_nme);
            ex.op.add(e);
            try {
                Connection con = getconnection1();
                java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO que_tbl_1(QUES,OP1,OP2,OP3,OP4,CORRECT_ANS,EXAM_ID,QUES_NUM)" + "values(?,?,?,?,?,?,?,?)");
                ps.setString(1, Ques_name.getText());
                ps.setString(2, frst.getText());

                ps.setString(3, scnd.getText());
                ps.setString(4, thrd.getText());
                ps.setString(5, frth.getText());
                ps.setString(6, Cor.getText());
                ps.setString(7, ex.exm_nme);
                ps.setString(8, que_num.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Question Added!");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            frst.setText(null);
            scnd.setText(null);
            thrd.setText(null);
            frth.setText(null);
            Cor.setText(null);
            Ques_name.setText("Question?");
            que_num.setText(1+".");

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ExamAdd.setVisible(true);
        set_exam.setVisible(false);
        Exam_name.setText(null);
        Ins.setText(null);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        set_exam.setVisible(false);
        Te_log.setVisible(true);
        tec_name.setText("");
        tec_pass.setText("");
        log_name.setText("");
        log_pass.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        set_exam.setVisible(false);
        Mark_sheet.setVisible(true);
        
        try{
            Connection con=getconnection1();
            String sql="select name,roll,marks from student_info where exam_name =? ";
            pst=con.prepareStatement(sql);
            pst.setString(1, search_exam.getText());
            rs=pst.executeQuery();
            marks_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Invalid Exam!");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed
        // TODO add your handling code here:
        
        if(st_name.getText().equals("") || st_roll.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Student information missing!");
        }
        else if(Ex_nm.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Exam name missing!");
        }
        else{
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from student_info where roll =? ");
            
            pst.setString(1, st_roll.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
                 JOptionPane.showMessageDialog(null,"Exam is already given by the student!");
            }
            else{
                try {
                    con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
                    pst=con.prepareStatement("select * from exam where name =? ");

                    pst.setString(1, Ex_nm.getText());

                    rs=pst.executeQuery();
                    if(rs.next()){
                         Stdnt_sub.setVisible(false);
                         exam_strt.setVisible(true);
                         instr =rs.getString("Instruction"); 
                         Instr_area.setText(instr);
                         E_NAM.setText(Ex_nm.getText());
                         instr =rs.getString("Time"); 
                         t_time.setText(instr);
                         instr =rs.getString("Marks"); 
                         t_marks.setText(instr);

                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Invalid Exam Name!");
                    }

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_Submit_buttonActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        Mark_sheet.setVisible(false);
        set_exam.setVisible(true);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void op4_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op4_radioActionPerformed

    private void op3_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op3_radioActionPerformed

    private void tec_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tec_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tec_passActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if (tec_name.getText().equals("")|| tec_pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "please insert data!");
        }
        else {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from teacher_info where name =? ");
            
            pst.setString(1, tec_name.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
                 JOptionPane.showMessageDialog(null, "Username Taken!");
            }
            else{
                te_reg.setVisible(false);
                Te_log.setVisible(true);
                try {
                Connection con = getconnection1();
                java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO teacher_info(name,pass)" + "values(?,?)");
                ps.setString(1, tec_name.getText());
                ps.setString(2, tec_pass.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "User Registered");

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        tec_name.setText("");
        tec_pass.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Te_log.setVisible(false);
        te_reg.setVisible(true);
        tec_name.setText("");
        tec_pass.setText("");
        log_name.setText("");
        log_pass.setText("");

    }//GEN-LAST:event_jButton13ActionPerformed

    private void thrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thrdActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

                ques e = new ques(Ques_name.getText(), frst.getText(), scnd.getText(), thrd.getText(), frth.getText(), Cor.getText(),ex.exm_nme);
                ex.op.add(e);
                try {
                    Connection con = getconnection1();
                    java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO que_tbl_1(QUES,OP1,OP2,OP3,OP4,CORRECT_ANS,EXAM_ID,QUES_NUM)" + "values(?,?,?,?,?,?,?,?)");
                    ps.setString(1, Ques_name.getText());
                    ps.setString(2, frst.getText());

                    ps.setString(3, scnd.getText());
                    ps.setString(4, thrd.getText());
                    ps.setString(5, frth.getText());
                    ps.setString(6, Cor.getText());
                    ps.setString(7, ex.exm_nme);
                    ps.setString(8, que_num.getText());

                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Question Added!");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                frst.setText(null);
                scnd.setText(null);
                thrd.setText(null);
                frth.setText(null);
                Cor.setText(null);
                Ques_name.setText(".Question?");
                que_num.setText(ex.op.size()+1+".");
                if(ex.op.size()==Integer.decode(marks.getText())){
                       set_que.setVisible(false);
                       set_exam.setVisible(true);
                       frst.setText(null);
                       scnd.setText(null);
                       thrd.setText(null);
                       frth.setText(null);
                       Cor.setText(null);
                       Ques_name.setText("Question?");
                       que_num.setText(1+".");
                       ex.op.clear();
                        try{
                            Connection con=getconnection1();
                            String sql="select name,Time,Marks from exam where Instructor =? ";
                            pst=con.prepareStatement(sql);
                            pst.setString(1, log_name.getText());
                            rs=pst.executeQuery();
                            exam_table.setModel(DbUtils.resultSetToTableModel(rs));

                        }
                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null, "Add You first exam!");
                        }
                }
                
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Te_log.setVisible(true);
        te_reg.setVisible(false);
        tec_name.setText("");
        tec_pass.setText("");
        log_name.setText("");
        log_pass.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void que_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_que_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_que_numActionPerformed

    private void frstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frstActionPerformed

    
    private void Next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_buttonActionPerformed
        // TODO add your handling code here:
            if(op1_radio.isSelected()){
                     if(op1_radio.getText().equals(instr)){
                        cur_marks=cur_marks+1;
                     }
                pdf ans=new pdf();
                ans.ques=ex_pg_ques.getText();
                ans.corans=instr;
                ans.givans=op1_radio.getText();
                pdf1.add(ans);
            }
            else if(op2_radio.isSelected()){
                     if(op2_radio.getText().equals(instr)){
                        cur_marks=cur_marks+1;
                     }
                   pdf ans=new pdf();
                   ans.ques=ex_pg_ques.getText();
                   ans.corans=instr;
                   ans.givans=op2_radio.getText();
                   pdf1.add(ans);
            }
            else if(op3_radio.isSelected()){
                     if(op3_radio.getText().equals(instr)){
                        cur_marks=cur_marks+1;
                     }
                     pdf ans=new pdf();
                    ans.ques=ex_pg_ques.getText();
                    ans.corans=instr;
                    ans.givans=op3_radio.getText();
                    pdf1.add(ans);
           }
           else if(op4_radio.isSelected()){
                     if(op4_radio.getText().equals(instr)){
                        cur_marks=cur_marks+1;
                     }
                    pdf ans=new pdf();
                    ans.ques=ex_pg_ques.getText();
                    ans.corans=instr;
                    ans.givans=op4_radio.getText();
                    pdf1.add(ans);
            }
            instr=null;
            op1_radio.setSelected(false);
            op2_radio.setSelected(false);
            op3_radio.setSelected(false);
            op4_radio.setSelected(false);
            que_pg_num++;
            que_num_ex_pg.setText(que_pg_num+".");
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from que_tbl_1 where EXAM_ID =? and QUES_NUM =?");
            
            
            pst.setString(1, Ex_nm.getText());
            pst.setString(2, que_num_ex_pg.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
                 exam_strt.setVisible(false);
                 exam_page.setVisible(true);
                 instr =rs.getString("QUES"); 
                 ex_pg_ques.setText(instr);
                 instr =rs.getString("OP1"); 
                 op1_radio.setText(instr);
                 instr =rs.getString("OP2"); 
                 op2_radio.setText(instr);
                 instr =rs.getString("OP3"); 
                 op3_radio.setText(instr);
                 instr =rs.getString("OP4"); 
                 op4_radio.setText(instr);
                 instr =rs.getString("CORRECT_ANS"); 
                 //JOptionPane.showMessageDialog(null, instr);
            }
            else{
                exam_page.setVisible(false);
                exam_finished.setVisible(true);
                ob_marks.setText(cur_marks+"");
                total_marks.setText(que_pg_num-1+"");
                try {
                    Connection con = getconnection1();
                    java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO student_info(name,roll,marks,exam_name)" + "values(?,?,?,?)");
                    ps.setString(1, st_name.getText());
                    ps.setString(2, st_roll.getText());

                    ps.setString(3, cur_marks+"");
                    ps.setString(4, Ex_nm.getText());
                    ps.executeUpdate();

                    //JOptionPane.showMessageDialog(null, "Data Inserted");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                
                cur_marks=0;
                ques_num = 0;
                que_pg_num=1;
                op1_radio.setSelected(false);
                op2_radio.setSelected(false);
                op3_radio.setSelected(false);
                op4_radio.setSelected(false);
                t.stop();
                JOptionPane.showMessageDialog(null,"Exam Finished");
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Next_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        exam_finished.setVisible(false);
        Stdnt_sub.setVisible(true);
        st_name.setText("");
        st_roll.setText("");
        Ex_nm.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        
        
        pdf1.clear();
        que_pg_num=1;
        que_num_ex_pg.setText(que_pg_num+".");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sazid", "root", "");
            pst=con.prepareStatement("select * from que_tbl_1 where EXAM_ID =? and QUES_NUM =?");

            pst.setString(1, Ex_nm.getText());
            pst.setString(2, que_num_ex_pg.getText());

            rs=pst.executeQuery();
            if(rs.next()){
                exam_strt.setVisible(false);
                exam_page.setVisible(true);
                instr =rs.getString("QUES");
                ex_pg_ques.setText(instr);
                instr =rs.getString("OP1");
                op1_radio.setText(instr);
                instr =rs.getString("OP2");
                op2_radio.setText(instr);
                instr =rs.getString("OP3");
                op3_radio.setText(instr);
                instr =rs.getString("OP4");
                op4_radio.setText(instr);
                instr =rs.getString("CORRECT_ANS");
                op1_radio.setSelected(false);
                op2_radio.setSelected(false);
                op3_radio.setSelected(false);
                op4_radio.setSelected(false);
                min=Integer.decode(t_time.getText())-1;
                sec=60;
                t=new Timer(1000,new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        sec--;
                        if(sec<10){
                             Timer_.setText(min+":0"+sec);
                        }
                        else Timer_.setText(min+":"+sec);
                        if(sec==0){
                            sec=60;
                            min=min-1;
                            if(min<0){
                                t.stop();
                                exam_page.setVisible(false);
                                exam_finished.setVisible(true);
                                ob_marks.setText(cur_marks+"");
                                total_marks.setText(t_marks.getText());
                                try {
                                    Connection con = getconnection1();
                                    java.sql.PreparedStatement ps = con.prepareStatement("INSERT INTO student_info(name,roll,marks,exam_name)" + "values(?,?,?,?)");
                                    ps.setString(1, st_name.getText());
                                    ps.setString(2, st_roll.getText());

                                    ps.setString(3, cur_marks+"");
                                    ps.setString(4, Ex_nm.getText());
                                    ps.executeUpdate();

                                    

                                } catch (SQLException ex) {
                                    JOptionPane.showMessageDialog(null, ex.getMessage());
                                }

                                cur_marks=0;
                                ques_num = 0;
                                que_pg_num=1;
                                op1_radio.setSelected(false);
                                op2_radio.setSelected(false);
                                op3_radio.setSelected(false);
                                op4_radio.setSelected(false);
                                JOptionPane.showMessageDialog(null,"Exam Finished");
                                
                            }
                        }
                    }
               
                });
                t.start();
                

            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Exam Name!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void pdf_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf_buttonActionPerformed
        try {
            // TODO add your handling code here:
            Document doc =new Document();
            try {
                PdfWriter.getInstance(doc, new FileOutputStream("Ans.pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(first.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            for(int i=0;i<pdf1.size();i++){
                doc.add(new Paragraph(i+1+". "+pdf1.get(i).ques+"\nCorrect ans: "+pdf1.get(i).corans +"\nGiven ans:"+ pdf1.get(i).givans+"\n\n"));
            }
            doc.close();
        } catch (DocumentException ex) {
            Logger.getLogger(first.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Your PDF is generated named as Ans.pdf!");
    }//GEN-LAST:event_pdf_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cor;
    private javax.swing.JLabel E_NAM;
    private javax.swing.JTextField Ex_nm;
    private javax.swing.JPanel ExamAdd;
    private javax.swing.JTextField Exam_name;
    private javax.swing.JTextArea Ins;
    private javax.swing.JTextArea Instr_area;
    private javax.swing.JPanel Mark_sheet;
    private javax.swing.JButton Next_button;
    private javax.swing.JTextArea Ques_name;
    private javax.swing.JPanel Stdnt_sub;
    private javax.swing.JButton Submit_button;
    private javax.swing.JPanel Te_log;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel Timer_;
    private javax.swing.JTextArea ex_pg_ques;
    private javax.swing.JPanel exam_finished;
    private javax.swing.JPanel exam_page;
    private javax.swing.JPanel exam_strt;
    private javax.swing.JTable exam_table;
    private javax.swing.JTextField frst;
    private javax.swing.JTextField frth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton lgin_btn;
    private javax.swing.JTextField log_name;
    private javax.swing.JPasswordField log_pass;
    private javax.swing.JTextField marks;
    private javax.swing.JTable marks_table;
    private javax.swing.JLabel ob_marks;
    private javax.swing.JRadioButton op1_radio;
    private javax.swing.JRadioButton op2_radio;
    private javax.swing.JRadioButton op3_radio;
    private javax.swing.JRadioButton op4_radio;
    private javax.swing.JButton pdf_button;
    private javax.swing.JTextField que_num;
    private javax.swing.JLabel que_num_ex_pg;
    private javax.swing.JTextField scnd;
    private javax.swing.JTextField search_exam;
    private javax.swing.JPanel set_exam;
    private javax.swing.JPanel set_que;
    private javax.swing.JTextField st_name;
    private javax.swing.JTextField st_roll;
    private javax.swing.JLabel t_marks;
    private javax.swing.JLabel t_time;
    private javax.swing.JPanel te_reg;
    private javax.swing.JTextField tec_name;
    private javax.swing.JTextField tec_pass;
    private javax.swing.JTextField thrd;
    private javax.swing.JTextField time;
    private javax.swing.JLabel total_marks;
    // End of variables declaration//GEN-END:variables
}
